---
- name: install nginx
  yum:
    name: nginx
    state: present
  tags:
    - repo

- name: enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - nginx

- name: sync nginx configs
  copy:
    src: /etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - configtest nginx
    - reload nginx
  tags:
    - nginx
    - nginx_config
